
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ThemeCustomizer': typeof import("../components/ThemeCustomizer.vue")['default']
    'BaseDatePicker': typeof import("../components/base/DatePicker.vue")['default']
    'BaseModal': typeof import("../components/base/Modal.vue")['default']
    'BaseMultiSelect': typeof import("../components/base/MultiSelect.vue")['default']
    'BaseMultiSelectt': typeof import("../components/base/MultiSelectt.vue")['default']
    'BaseUpload': typeof import("../components/base/Upload.vue")['default']
    'ClientAddClient': typeof import("../components/client/AddClient.vue")['default']
    'ClientTag': typeof import("../components/client/Tag.vue")['default']
    'FormCheckbox': typeof import("../components/form/Checkbox.vue")['default']
    'FormInput': typeof import("../components/form/Input.vue")['default']
    'FormPriceInput': typeof import("../components/form/PriceInput.vue")['default']
    'FormRadio': typeof import("../components/form/Radio.vue")['default']
    'FormTextarea': typeof import("../components/form/Textarea.vue")['default']
    'IconCompany': typeof import("../components/icon/Company.vue")['default']
    'IconAirplay': typeof import("../components/icon/icon-airplay.vue")['default']
    'IconArchive': typeof import("../components/icon/icon-archive.vue")['default']
    'IconArrowBackward': typeof import("../components/icon/icon-arrow-backward.vue")['default']
    'IconArrowForward': typeof import("../components/icon/icon-arrow-forward.vue")['default']
    'IconArrowLeft': typeof import("../components/icon/icon-arrow-left.vue")['default']
    'IconArrowWaveLeftUp': typeof import("../components/icon/icon-arrow-wave-left-up.vue")['default']
    'IconAt': typeof import("../components/icon/icon-at.vue")['default']
    'IconAward': typeof import("../components/icon/icon-award.vue")['default']
    'IconBarChart': typeof import("../components/icon/icon-bar-chart.vue")['default']
    'IconBellBing': typeof import("../components/icon/icon-bell-bing.vue")['default']
    'IconBell': typeof import("../components/icon/icon-bell.vue")['default']
    'IconBinance': typeof import("../components/icon/icon-binance.vue")['default']
    'IconBitcoin': typeof import("../components/icon/icon-bitcoin.vue")['default']
    'IconBolt': typeof import("../components/icon/icon-bolt.vue")['default']
    'IconBook': typeof import("../components/icon/icon-book.vue")['default']
    'IconBookmark': typeof import("../components/icon/icon-bookmark.vue")['default']
    'IconBox': typeof import("../components/icon/icon-box.vue")['default']
    'IconCalendar': typeof import("../components/icon/icon-calendar.vue")['default']
    'IconCamera': typeof import("../components/icon/icon-camera.vue")['default']
    'IconCaretDown': typeof import("../components/icon/icon-caret-down.vue")['default']
    'IconCaretsDown': typeof import("../components/icon/icon-carets-down.vue")['default']
    'IconCashBanknotes': typeof import("../components/icon/icon-cash-banknotes.vue")['default']
    'IconChartSquare': typeof import("../components/icon/icon-chart-square.vue")['default']
    'IconChatDot': typeof import("../components/icon/icon-chat-dot.vue")['default']
    'IconChatDots': typeof import("../components/icon/icon-chat-dots.vue")['default']
    'IconChatNotification': typeof import("../components/icon/icon-chat-notification.vue")['default']
    'IconChecks': typeof import("../components/icon/icon-checks.vue")['default']
    'IconChrome': typeof import("../components/icon/icon-chrome.vue")['default']
    'IconCircleCheck': typeof import("../components/icon/icon-circle-check.vue")['default']
    'IconClipboardText': typeof import("../components/icon/icon-clipboard-text.vue")['default']
    'IconClock': typeof import("../components/icon/icon-clock.vue")['default']
    'IconCloudDownload': typeof import("../components/icon/icon-cloud-download.vue")['default']
    'IconCode': typeof import("../components/icon/icon-code.vue")['default']
    'IconCoffee': typeof import("../components/icon/icon-coffee.vue")['default']
    'IconCopy': typeof import("../components/icon/icon-copy.vue")['default']
    'IconCpuBolt': typeof import("../components/icon/icon-cpu-bolt.vue")['default']
    'IconCreditCard': typeof import("../components/icon/icon-credit-card.vue")['default']
    'IconDesktop': typeof import("../components/icon/icon-desktop.vue")['default']
    'IconDollarSignCircle': typeof import("../components/icon/icon-dollar-sign-circle.vue")['default']
    'IconDollarSign': typeof import("../components/icon/icon-dollar-sign.vue")['default']
    'IconDownload': typeof import("../components/icon/icon-download.vue")['default']
    'IconDribbble': typeof import("../components/icon/icon-dribbble.vue")['default']
    'IconDroplet': typeof import("../components/icon/icon-droplet.vue")['default']
    'IconEdit': typeof import("../components/icon/icon-edit.vue")['default']
    'IconEthereum': typeof import("../components/icon/icon-ethereum.vue")['default']
    'IconEye': typeof import("../components/icon/icon-eye.vue")['default']
    'IconFacebookCircle': typeof import("../components/icon/icon-facebook-circle.vue")['default']
    'IconFacebook': typeof import("../components/icon/icon-facebook.vue")['default']
    'IconFile': typeof import("../components/icon/icon-file.vue")['default']
    'IconFolderMinus': typeof import("../components/icon/icon-folder-minus.vue")['default']
    'IconFolderPlus': typeof import("../components/icon/icon-folder-plus.vue")['default']
    'IconFolder': typeof import("../components/icon/icon-folder.vue")['default']
    'IconGallery': typeof import("../components/icon/icon-gallery.vue")['default']
    'IconGithub': typeof import("../components/icon/icon-github.vue")['default']
    'IconGlobe': typeof import("../components/icon/icon-globe.vue")['default']
    'IconGoogle': typeof import("../components/icon/icon-google.vue")['default']
    'IconHeart': typeof import("../components/icon/icon-heart.vue")['default']
    'IconHelpCircle': typeof import("../components/icon/icon-help-circle.vue")['default']
    'IconHome': typeof import("../components/icon/icon-home.vue")['default']
    'IconHorizontalDots': typeof import("../components/icon/icon-horizontal-dots.vue")['default']
    'IconInbox': typeof import("../components/icon/icon-inbox.vue")['default']
    'IconInfoCircle': typeof import("../components/icon/icon-info-circle.vue")['default']
    'IconInfoHexagon': typeof import("../components/icon/icon-info-hexagon.vue")['default']
    'IconInfoTriangle': typeof import("../components/icon/icon-info-triangle.vue")['default']
    'IconInstagram': typeof import("../components/icon/icon-instagram.vue")['default']
    'IconLaptop': typeof import("../components/icon/icon-laptop.vue")['default']
    'IconLayoutGrid': typeof import("../components/icon/icon-layout-grid.vue")['default']
    'IconLayout': typeof import("../components/icon/icon-layout.vue")['default']
    'IconLink': typeof import("../components/icon/icon-link.vue")['default']
    'IconLinkedin': typeof import("../components/icon/icon-linkedin.vue")['default']
    'IconListCheck': typeof import("../components/icon/icon-list-check.vue")['default']
    'IconLitecoin': typeof import("../components/icon/icon-litecoin.vue")['default']
    'IconLoader': typeof import("../components/icon/icon-loader.vue")['default']
    'IconLockDots': typeof import("../components/icon/icon-lock-dots.vue")['default']
    'IconLock': typeof import("../components/icon/icon-lock.vue")['default']
    'IconLogin': typeof import("../components/icon/icon-login.vue")['default']
    'IconLogout': typeof import("../components/icon/icon-logout.vue")['default']
    'IconMailDot': typeof import("../components/icon/icon-mail-dot.vue")['default']
    'IconMail': typeof import("../components/icon/icon-mail.vue")['default']
    'IconMapPin': typeof import("../components/icon/icon-map-pin.vue")['default']
    'IconMenu': typeof import("../components/icon/icon-menu.vue")['default']
    'IconMessage2': typeof import("../components/icon/icon-message-2.vue")['default']
    'IconMessageDots': typeof import("../components/icon/icon-message-dots.vue")['default']
    'IconMessage': typeof import("../components/icon/icon-message.vue")['default']
    'IconMessagesDot': typeof import("../components/icon/icon-messages-dot.vue")['default']
    'IconMicrophoneOff': typeof import("../components/icon/icon-microphone-off.vue")['default']
    'IconMinusCircle': typeof import("../components/icon/icon-minus-circle.vue")['default']
    'IconMinus': typeof import("../components/icon/icon-minus.vue")['default']
    'IconMoodSmile': typeof import("../components/icon/icon-mood-smile.vue")['default']
    'IconMoon': typeof import("../components/icon/icon-moon.vue")['default']
    'IconMultipleForwardRight': typeof import("../components/icon/icon-multiple-forward-right.vue")['default']
    'IconNetflix': typeof import("../components/icon/icon-netflix.vue")['default']
    'IconNotesEdit': typeof import("../components/icon/icon-notes-edit.vue")['default']
    'IconNotes': typeof import("../components/icon/icon-notes.vue")['default']
    'IconOpenBook': typeof import("../components/icon/icon-open-book.vue")['default']
    'IconPaperclip': typeof import("../components/icon/icon-paperclip.vue")['default']
    'IconPencilPaper': typeof import("../components/icon/icon-pencil-paper.vue")['default']
    'IconPencil': typeof import("../components/icon/icon-pencil.vue")['default']
    'IconPhoneCall': typeof import("../components/icon/icon-phone-call.vue")['default']
    'IconPhone': typeof import("../components/icon/icon-phone.vue")['default']
    'IconPlayCircle': typeof import("../components/icon/icon-play-circle.vue")['default']
    'IconPlusCircle': typeof import("../components/icon/icon-plus-circle.vue")['default']
    'IconPlus': typeof import("../components/icon/icon-plus.vue")['default']
    'IconPrinter': typeof import("../components/icon/icon-printer.vue")['default']
    'IconRefresh': typeof import("../components/icon/icon-refresh.vue")['default']
    'IconRestore': typeof import("../components/icon/icon-restore.vue")['default']
    'IconRouter': typeof import("../components/icon/icon-router.vue")['default']
    'IconSafari': typeof import("../components/icon/icon-safari.vue")['default']
    'IconSave': typeof import("../components/icon/icon-save.vue")['default']
    'IconSearch': typeof import("../components/icon/icon-search.vue")['default']
    'IconSend': typeof import("../components/icon/icon-send.vue")['default']
    'IconServer': typeof import("../components/icon/icon-server.vue")['default']
    'IconSettings': typeof import("../components/icon/icon-settings.vue")['default']
    'IconShare': typeof import("../components/icon/icon-share.vue")['default']
    'IconShoppingBag': typeof import("../components/icon/icon-shopping-bag.vue")['default']
    'IconShoppingCart': typeof import("../components/icon/icon-shopping-cart.vue")['default']
    'IconSolana': typeof import("../components/icon/icon-solana.vue")['default']
    'IconSquareCheck': typeof import("../components/icon/icon-square-check.vue")['default']
    'IconSquareRotated': typeof import("../components/icon/icon-square-rotated.vue")['default']
    'IconStar': typeof import("../components/icon/icon-star.vue")['default']
    'IconSun': typeof import("../components/icon/icon-sun.vue")['default']
    'IconTag': typeof import("../components/icon/icon-tag.vue")['default']
    'IconTether': typeof import("../components/icon/icon-tether.vue")['default']
    'IconThumbUp': typeof import("../components/icon/icon-thumb-up.vue")['default']
    'IconTrashLines': typeof import("../components/icon/icon-trash-lines.vue")['default']
    'IconTrash': typeof import("../components/icon/icon-trash.vue")['default']
    'IconTrendingUp': typeof import("../components/icon/icon-trending-up.vue")['default']
    'IconTwitter': typeof import("../components/icon/icon-twitter.vue")['default']
    'IconTxtFile': typeof import("../components/icon/icon-txt-file.vue")['default']
    'IconUserPlus': typeof import("../components/icon/icon-user-plus.vue")['default']
    'IconUser': typeof import("../components/icon/icon-user.vue")['default']
    'IconUsersGroup': typeof import("../components/icon/icon-users-group.vue")['default']
    'IconUsers': typeof import("../components/icon/icon-users.vue")['default']
    'IconVideo': typeof import("../components/icon/icon-video.vue")['default']
    'IconWheel': typeof import("../components/icon/icon-wheel.vue")['default']
    'IconXCircle': typeof import("../components/icon/icon-x-circle.vue")['default']
    'IconX': typeof import("../components/icon/icon-x.vue")['default']
    'IconZipFile': typeof import("../components/icon/icon-zip-file.vue")['default']
    'IconMenuApps': typeof import("../components/icon/menu/icon-menu-apps.vue")['default']
    'IconMenuAuthentication': typeof import("../components/icon/menu/icon-menu-authentication.vue")['default']
    'IconMenuCalendar': typeof import("../components/icon/menu/icon-menu-calendar.vue")['default']
    'IconMenuCharts': typeof import("../components/icon/menu/icon-menu-charts.vue")['default']
    'IconMenuChat': typeof import("../components/icon/menu/icon-menu-chat.vue")['default']
    'IconMenuComponents': typeof import("../components/icon/menu/icon-menu-components.vue")['default']
    'IconMenuContacts': typeof import("../components/icon/menu/icon-menu-contacts.vue")['default']
    'IconMenuDashboard': typeof import("../components/icon/menu/icon-menu-dashboard.vue")['default']
    'IconMenuDatatables': typeof import("../components/icon/menu/icon-menu-datatables.vue")['default']
    'IconMenuDocumentation': typeof import("../components/icon/menu/icon-menu-documentation.vue")['default']
    'IconMenuDragAndDrop': typeof import("../components/icon/menu/icon-menu-drag-and-drop.vue")['default']
    'IconMenuElements': typeof import("../components/icon/menu/icon-menu-elements.vue")['default']
    'IconMenuFontIcons': typeof import("../components/icon/menu/icon-menu-font-icons.vue")['default']
    'IconMenuForms': typeof import("../components/icon/menu/icon-menu-forms.vue")['default']
    'IconMenuInvoice': typeof import("../components/icon/menu/icon-menu-invoice.vue")['default']
    'IconMenuMailbox': typeof import("../components/icon/menu/icon-menu-mailbox.vue")['default']
    'IconMenuMore': typeof import("../components/icon/menu/icon-menu-more.vue")['default']
    'IconMenuNotes': typeof import("../components/icon/menu/icon-menu-notes.vue")['default']
    'IconMenuPages': typeof import("../components/icon/menu/icon-menu-pages.vue")['default']
    'IconMenuScrumboard': typeof import("../components/icon/menu/icon-menu-scrumboard.vue")['default']
    'IconMenuTables': typeof import("../components/icon/menu/icon-menu-tables.vue")['default']
    'IconMenuTodo': typeof import("../components/icon/menu/icon-menu-todo.vue")['default']
    'IconMenuUsers': typeof import("../components/icon/menu/icon-menu-users.vue")['default']
    'IconMenuWidgets': typeof import("../components/icon/menu/icon-menu-widgets.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LayoutSidebar': typeof import("../components/layout/Sidebar.vue")['default']
    'MatterAdd': typeof import("../components/matter/Add.vue")['default']
    'PluginsHighlight': typeof import("../components/plugins/highlight.vue")['default']
    'TaskAdd': typeof import("../components/task/Add.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyThemeCustomizer': typeof import("../components/ThemeCustomizer.vue")['default']
    'LazyBaseDatePicker': typeof import("../components/base/DatePicker.vue")['default']
    'LazyBaseModal': typeof import("../components/base/Modal.vue")['default']
    'LazyBaseMultiSelect': typeof import("../components/base/MultiSelect.vue")['default']
    'LazyBaseMultiSelectt': typeof import("../components/base/MultiSelectt.vue")['default']
    'LazyBaseUpload': typeof import("../components/base/Upload.vue")['default']
    'LazyClientAddClient': typeof import("../components/client/AddClient.vue")['default']
    'LazyClientTag': typeof import("../components/client/Tag.vue")['default']
    'LazyFormCheckbox': typeof import("../components/form/Checkbox.vue")['default']
    'LazyFormInput': typeof import("../components/form/Input.vue")['default']
    'LazyFormPriceInput': typeof import("../components/form/PriceInput.vue")['default']
    'LazyFormRadio': typeof import("../components/form/Radio.vue")['default']
    'LazyFormTextarea': typeof import("../components/form/Textarea.vue")['default']
    'LazyIconCompany': typeof import("../components/icon/Company.vue")['default']
    'LazyIconAirplay': typeof import("../components/icon/icon-airplay.vue")['default']
    'LazyIconArchive': typeof import("../components/icon/icon-archive.vue")['default']
    'LazyIconArrowBackward': typeof import("../components/icon/icon-arrow-backward.vue")['default']
    'LazyIconArrowForward': typeof import("../components/icon/icon-arrow-forward.vue")['default']
    'LazyIconArrowLeft': typeof import("../components/icon/icon-arrow-left.vue")['default']
    'LazyIconArrowWaveLeftUp': typeof import("../components/icon/icon-arrow-wave-left-up.vue")['default']
    'LazyIconAt': typeof import("../components/icon/icon-at.vue")['default']
    'LazyIconAward': typeof import("../components/icon/icon-award.vue")['default']
    'LazyIconBarChart': typeof import("../components/icon/icon-bar-chart.vue")['default']
    'LazyIconBellBing': typeof import("../components/icon/icon-bell-bing.vue")['default']
    'LazyIconBell': typeof import("../components/icon/icon-bell.vue")['default']
    'LazyIconBinance': typeof import("../components/icon/icon-binance.vue")['default']
    'LazyIconBitcoin': typeof import("../components/icon/icon-bitcoin.vue")['default']
    'LazyIconBolt': typeof import("../components/icon/icon-bolt.vue")['default']
    'LazyIconBook': typeof import("../components/icon/icon-book.vue")['default']
    'LazyIconBookmark': typeof import("../components/icon/icon-bookmark.vue")['default']
    'LazyIconBox': typeof import("../components/icon/icon-box.vue")['default']
    'LazyIconCalendar': typeof import("../components/icon/icon-calendar.vue")['default']
    'LazyIconCamera': typeof import("../components/icon/icon-camera.vue")['default']
    'LazyIconCaretDown': typeof import("../components/icon/icon-caret-down.vue")['default']
    'LazyIconCaretsDown': typeof import("../components/icon/icon-carets-down.vue")['default']
    'LazyIconCashBanknotes': typeof import("../components/icon/icon-cash-banknotes.vue")['default']
    'LazyIconChartSquare': typeof import("../components/icon/icon-chart-square.vue")['default']
    'LazyIconChatDot': typeof import("../components/icon/icon-chat-dot.vue")['default']
    'LazyIconChatDots': typeof import("../components/icon/icon-chat-dots.vue")['default']
    'LazyIconChatNotification': typeof import("../components/icon/icon-chat-notification.vue")['default']
    'LazyIconChecks': typeof import("../components/icon/icon-checks.vue")['default']
    'LazyIconChrome': typeof import("../components/icon/icon-chrome.vue")['default']
    'LazyIconCircleCheck': typeof import("../components/icon/icon-circle-check.vue")['default']
    'LazyIconClipboardText': typeof import("../components/icon/icon-clipboard-text.vue")['default']
    'LazyIconClock': typeof import("../components/icon/icon-clock.vue")['default']
    'LazyIconCloudDownload': typeof import("../components/icon/icon-cloud-download.vue")['default']
    'LazyIconCode': typeof import("../components/icon/icon-code.vue")['default']
    'LazyIconCoffee': typeof import("../components/icon/icon-coffee.vue")['default']
    'LazyIconCopy': typeof import("../components/icon/icon-copy.vue")['default']
    'LazyIconCpuBolt': typeof import("../components/icon/icon-cpu-bolt.vue")['default']
    'LazyIconCreditCard': typeof import("../components/icon/icon-credit-card.vue")['default']
    'LazyIconDesktop': typeof import("../components/icon/icon-desktop.vue")['default']
    'LazyIconDollarSignCircle': typeof import("../components/icon/icon-dollar-sign-circle.vue")['default']
    'LazyIconDollarSign': typeof import("../components/icon/icon-dollar-sign.vue")['default']
    'LazyIconDownload': typeof import("../components/icon/icon-download.vue")['default']
    'LazyIconDribbble': typeof import("../components/icon/icon-dribbble.vue")['default']
    'LazyIconDroplet': typeof import("../components/icon/icon-droplet.vue")['default']
    'LazyIconEdit': typeof import("../components/icon/icon-edit.vue")['default']
    'LazyIconEthereum': typeof import("../components/icon/icon-ethereum.vue")['default']
    'LazyIconEye': typeof import("../components/icon/icon-eye.vue")['default']
    'LazyIconFacebookCircle': typeof import("../components/icon/icon-facebook-circle.vue")['default']
    'LazyIconFacebook': typeof import("../components/icon/icon-facebook.vue")['default']
    'LazyIconFile': typeof import("../components/icon/icon-file.vue")['default']
    'LazyIconFolderMinus': typeof import("../components/icon/icon-folder-minus.vue")['default']
    'LazyIconFolderPlus': typeof import("../components/icon/icon-folder-plus.vue")['default']
    'LazyIconFolder': typeof import("../components/icon/icon-folder.vue")['default']
    'LazyIconGallery': typeof import("../components/icon/icon-gallery.vue")['default']
    'LazyIconGithub': typeof import("../components/icon/icon-github.vue")['default']
    'LazyIconGlobe': typeof import("../components/icon/icon-globe.vue")['default']
    'LazyIconGoogle': typeof import("../components/icon/icon-google.vue")['default']
    'LazyIconHeart': typeof import("../components/icon/icon-heart.vue")['default']
    'LazyIconHelpCircle': typeof import("../components/icon/icon-help-circle.vue")['default']
    'LazyIconHome': typeof import("../components/icon/icon-home.vue")['default']
    'LazyIconHorizontalDots': typeof import("../components/icon/icon-horizontal-dots.vue")['default']
    'LazyIconInbox': typeof import("../components/icon/icon-inbox.vue")['default']
    'LazyIconInfoCircle': typeof import("../components/icon/icon-info-circle.vue")['default']
    'LazyIconInfoHexagon': typeof import("../components/icon/icon-info-hexagon.vue")['default']
    'LazyIconInfoTriangle': typeof import("../components/icon/icon-info-triangle.vue")['default']
    'LazyIconInstagram': typeof import("../components/icon/icon-instagram.vue")['default']
    'LazyIconLaptop': typeof import("../components/icon/icon-laptop.vue")['default']
    'LazyIconLayoutGrid': typeof import("../components/icon/icon-layout-grid.vue")['default']
    'LazyIconLayout': typeof import("../components/icon/icon-layout.vue")['default']
    'LazyIconLink': typeof import("../components/icon/icon-link.vue")['default']
    'LazyIconLinkedin': typeof import("../components/icon/icon-linkedin.vue")['default']
    'LazyIconListCheck': typeof import("../components/icon/icon-list-check.vue")['default']
    'LazyIconLitecoin': typeof import("../components/icon/icon-litecoin.vue")['default']
    'LazyIconLoader': typeof import("../components/icon/icon-loader.vue")['default']
    'LazyIconLockDots': typeof import("../components/icon/icon-lock-dots.vue")['default']
    'LazyIconLock': typeof import("../components/icon/icon-lock.vue")['default']
    'LazyIconLogin': typeof import("../components/icon/icon-login.vue")['default']
    'LazyIconLogout': typeof import("../components/icon/icon-logout.vue")['default']
    'LazyIconMailDot': typeof import("../components/icon/icon-mail-dot.vue")['default']
    'LazyIconMail': typeof import("../components/icon/icon-mail.vue")['default']
    'LazyIconMapPin': typeof import("../components/icon/icon-map-pin.vue")['default']
    'LazyIconMenu': typeof import("../components/icon/icon-menu.vue")['default']
    'LazyIconMessage2': typeof import("../components/icon/icon-message-2.vue")['default']
    'LazyIconMessageDots': typeof import("../components/icon/icon-message-dots.vue")['default']
    'LazyIconMessage': typeof import("../components/icon/icon-message.vue")['default']
    'LazyIconMessagesDot': typeof import("../components/icon/icon-messages-dot.vue")['default']
    'LazyIconMicrophoneOff': typeof import("../components/icon/icon-microphone-off.vue")['default']
    'LazyIconMinusCircle': typeof import("../components/icon/icon-minus-circle.vue")['default']
    'LazyIconMinus': typeof import("../components/icon/icon-minus.vue")['default']
    'LazyIconMoodSmile': typeof import("../components/icon/icon-mood-smile.vue")['default']
    'LazyIconMoon': typeof import("../components/icon/icon-moon.vue")['default']
    'LazyIconMultipleForwardRight': typeof import("../components/icon/icon-multiple-forward-right.vue")['default']
    'LazyIconNetflix': typeof import("../components/icon/icon-netflix.vue")['default']
    'LazyIconNotesEdit': typeof import("../components/icon/icon-notes-edit.vue")['default']
    'LazyIconNotes': typeof import("../components/icon/icon-notes.vue")['default']
    'LazyIconOpenBook': typeof import("../components/icon/icon-open-book.vue")['default']
    'LazyIconPaperclip': typeof import("../components/icon/icon-paperclip.vue")['default']
    'LazyIconPencilPaper': typeof import("../components/icon/icon-pencil-paper.vue")['default']
    'LazyIconPencil': typeof import("../components/icon/icon-pencil.vue")['default']
    'LazyIconPhoneCall': typeof import("../components/icon/icon-phone-call.vue")['default']
    'LazyIconPhone': typeof import("../components/icon/icon-phone.vue")['default']
    'LazyIconPlayCircle': typeof import("../components/icon/icon-play-circle.vue")['default']
    'LazyIconPlusCircle': typeof import("../components/icon/icon-plus-circle.vue")['default']
    'LazyIconPlus': typeof import("../components/icon/icon-plus.vue")['default']
    'LazyIconPrinter': typeof import("../components/icon/icon-printer.vue")['default']
    'LazyIconRefresh': typeof import("../components/icon/icon-refresh.vue")['default']
    'LazyIconRestore': typeof import("../components/icon/icon-restore.vue")['default']
    'LazyIconRouter': typeof import("../components/icon/icon-router.vue")['default']
    'LazyIconSafari': typeof import("../components/icon/icon-safari.vue")['default']
    'LazyIconSave': typeof import("../components/icon/icon-save.vue")['default']
    'LazyIconSearch': typeof import("../components/icon/icon-search.vue")['default']
    'LazyIconSend': typeof import("../components/icon/icon-send.vue")['default']
    'LazyIconServer': typeof import("../components/icon/icon-server.vue")['default']
    'LazyIconSettings': typeof import("../components/icon/icon-settings.vue")['default']
    'LazyIconShare': typeof import("../components/icon/icon-share.vue")['default']
    'LazyIconShoppingBag': typeof import("../components/icon/icon-shopping-bag.vue")['default']
    'LazyIconShoppingCart': typeof import("../components/icon/icon-shopping-cart.vue")['default']
    'LazyIconSolana': typeof import("../components/icon/icon-solana.vue")['default']
    'LazyIconSquareCheck': typeof import("../components/icon/icon-square-check.vue")['default']
    'LazyIconSquareRotated': typeof import("../components/icon/icon-square-rotated.vue")['default']
    'LazyIconStar': typeof import("../components/icon/icon-star.vue")['default']
    'LazyIconSun': typeof import("../components/icon/icon-sun.vue")['default']
    'LazyIconTag': typeof import("../components/icon/icon-tag.vue")['default']
    'LazyIconTether': typeof import("../components/icon/icon-tether.vue")['default']
    'LazyIconThumbUp': typeof import("../components/icon/icon-thumb-up.vue")['default']
    'LazyIconTrashLines': typeof import("../components/icon/icon-trash-lines.vue")['default']
    'LazyIconTrash': typeof import("../components/icon/icon-trash.vue")['default']
    'LazyIconTrendingUp': typeof import("../components/icon/icon-trending-up.vue")['default']
    'LazyIconTwitter': typeof import("../components/icon/icon-twitter.vue")['default']
    'LazyIconTxtFile': typeof import("../components/icon/icon-txt-file.vue")['default']
    'LazyIconUserPlus': typeof import("../components/icon/icon-user-plus.vue")['default']
    'LazyIconUser': typeof import("../components/icon/icon-user.vue")['default']
    'LazyIconUsersGroup': typeof import("../components/icon/icon-users-group.vue")['default']
    'LazyIconUsers': typeof import("../components/icon/icon-users.vue")['default']
    'LazyIconVideo': typeof import("../components/icon/icon-video.vue")['default']
    'LazyIconWheel': typeof import("../components/icon/icon-wheel.vue")['default']
    'LazyIconXCircle': typeof import("../components/icon/icon-x-circle.vue")['default']
    'LazyIconX': typeof import("../components/icon/icon-x.vue")['default']
    'LazyIconZipFile': typeof import("../components/icon/icon-zip-file.vue")['default']
    'LazyIconMenuApps': typeof import("../components/icon/menu/icon-menu-apps.vue")['default']
    'LazyIconMenuAuthentication': typeof import("../components/icon/menu/icon-menu-authentication.vue")['default']
    'LazyIconMenuCalendar': typeof import("../components/icon/menu/icon-menu-calendar.vue")['default']
    'LazyIconMenuCharts': typeof import("../components/icon/menu/icon-menu-charts.vue")['default']
    'LazyIconMenuChat': typeof import("../components/icon/menu/icon-menu-chat.vue")['default']
    'LazyIconMenuComponents': typeof import("../components/icon/menu/icon-menu-components.vue")['default']
    'LazyIconMenuContacts': typeof import("../components/icon/menu/icon-menu-contacts.vue")['default']
    'LazyIconMenuDashboard': typeof import("../components/icon/menu/icon-menu-dashboard.vue")['default']
    'LazyIconMenuDatatables': typeof import("../components/icon/menu/icon-menu-datatables.vue")['default']
    'LazyIconMenuDocumentation': typeof import("../components/icon/menu/icon-menu-documentation.vue")['default']
    'LazyIconMenuDragAndDrop': typeof import("../components/icon/menu/icon-menu-drag-and-drop.vue")['default']
    'LazyIconMenuElements': typeof import("../components/icon/menu/icon-menu-elements.vue")['default']
    'LazyIconMenuFontIcons': typeof import("../components/icon/menu/icon-menu-font-icons.vue")['default']
    'LazyIconMenuForms': typeof import("../components/icon/menu/icon-menu-forms.vue")['default']
    'LazyIconMenuInvoice': typeof import("../components/icon/menu/icon-menu-invoice.vue")['default']
    'LazyIconMenuMailbox': typeof import("../components/icon/menu/icon-menu-mailbox.vue")['default']
    'LazyIconMenuMore': typeof import("../components/icon/menu/icon-menu-more.vue")['default']
    'LazyIconMenuNotes': typeof import("../components/icon/menu/icon-menu-notes.vue")['default']
    'LazyIconMenuPages': typeof import("../components/icon/menu/icon-menu-pages.vue")['default']
    'LazyIconMenuScrumboard': typeof import("../components/icon/menu/icon-menu-scrumboard.vue")['default']
    'LazyIconMenuTables': typeof import("../components/icon/menu/icon-menu-tables.vue")['default']
    'LazyIconMenuTodo': typeof import("../components/icon/menu/icon-menu-todo.vue")['default']
    'LazyIconMenuUsers': typeof import("../components/icon/menu/icon-menu-users.vue")['default']
    'LazyIconMenuWidgets': typeof import("../components/icon/menu/icon-menu-widgets.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LazyLayoutSidebar': typeof import("../components/layout/Sidebar.vue")['default']
    'LazyMatterAdd': typeof import("../components/matter/Add.vue")['default']
    'LazyPluginsHighlight': typeof import("../components/plugins/highlight.vue")['default']
    'LazyTaskAdd': typeof import("../components/task/Add.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ThemeCustomizer: typeof import("../components/ThemeCustomizer.vue")['default']
export const BaseDatePicker: typeof import("../components/base/DatePicker.vue")['default']
export const BaseModal: typeof import("../components/base/Modal.vue")['default']
export const BaseMultiSelect: typeof import("../components/base/MultiSelect.vue")['default']
export const BaseMultiSelectt: typeof import("../components/base/MultiSelectt.vue")['default']
export const BaseUpload: typeof import("../components/base/Upload.vue")['default']
export const ClientAddClient: typeof import("../components/client/AddClient.vue")['default']
export const ClientTag: typeof import("../components/client/Tag.vue")['default']
export const FormCheckbox: typeof import("../components/form/Checkbox.vue")['default']
export const FormInput: typeof import("../components/form/Input.vue")['default']
export const FormPriceInput: typeof import("../components/form/PriceInput.vue")['default']
export const FormRadio: typeof import("../components/form/Radio.vue")['default']
export const FormTextarea: typeof import("../components/form/Textarea.vue")['default']
export const IconCompany: typeof import("../components/icon/Company.vue")['default']
export const IconAirplay: typeof import("../components/icon/icon-airplay.vue")['default']
export const IconArchive: typeof import("../components/icon/icon-archive.vue")['default']
export const IconArrowBackward: typeof import("../components/icon/icon-arrow-backward.vue")['default']
export const IconArrowForward: typeof import("../components/icon/icon-arrow-forward.vue")['default']
export const IconArrowLeft: typeof import("../components/icon/icon-arrow-left.vue")['default']
export const IconArrowWaveLeftUp: typeof import("../components/icon/icon-arrow-wave-left-up.vue")['default']
export const IconAt: typeof import("../components/icon/icon-at.vue")['default']
export const IconAward: typeof import("../components/icon/icon-award.vue")['default']
export const IconBarChart: typeof import("../components/icon/icon-bar-chart.vue")['default']
export const IconBellBing: typeof import("../components/icon/icon-bell-bing.vue")['default']
export const IconBell: typeof import("../components/icon/icon-bell.vue")['default']
export const IconBinance: typeof import("../components/icon/icon-binance.vue")['default']
export const IconBitcoin: typeof import("../components/icon/icon-bitcoin.vue")['default']
export const IconBolt: typeof import("../components/icon/icon-bolt.vue")['default']
export const IconBook: typeof import("../components/icon/icon-book.vue")['default']
export const IconBookmark: typeof import("../components/icon/icon-bookmark.vue")['default']
export const IconBox: typeof import("../components/icon/icon-box.vue")['default']
export const IconCalendar: typeof import("../components/icon/icon-calendar.vue")['default']
export const IconCamera: typeof import("../components/icon/icon-camera.vue")['default']
export const IconCaretDown: typeof import("../components/icon/icon-caret-down.vue")['default']
export const IconCaretsDown: typeof import("../components/icon/icon-carets-down.vue")['default']
export const IconCashBanknotes: typeof import("../components/icon/icon-cash-banknotes.vue")['default']
export const IconChartSquare: typeof import("../components/icon/icon-chart-square.vue")['default']
export const IconChatDot: typeof import("../components/icon/icon-chat-dot.vue")['default']
export const IconChatDots: typeof import("../components/icon/icon-chat-dots.vue")['default']
export const IconChatNotification: typeof import("../components/icon/icon-chat-notification.vue")['default']
export const IconChecks: typeof import("../components/icon/icon-checks.vue")['default']
export const IconChrome: typeof import("../components/icon/icon-chrome.vue")['default']
export const IconCircleCheck: typeof import("../components/icon/icon-circle-check.vue")['default']
export const IconClipboardText: typeof import("../components/icon/icon-clipboard-text.vue")['default']
export const IconClock: typeof import("../components/icon/icon-clock.vue")['default']
export const IconCloudDownload: typeof import("../components/icon/icon-cloud-download.vue")['default']
export const IconCode: typeof import("../components/icon/icon-code.vue")['default']
export const IconCoffee: typeof import("../components/icon/icon-coffee.vue")['default']
export const IconCopy: typeof import("../components/icon/icon-copy.vue")['default']
export const IconCpuBolt: typeof import("../components/icon/icon-cpu-bolt.vue")['default']
export const IconCreditCard: typeof import("../components/icon/icon-credit-card.vue")['default']
export const IconDesktop: typeof import("../components/icon/icon-desktop.vue")['default']
export const IconDollarSignCircle: typeof import("../components/icon/icon-dollar-sign-circle.vue")['default']
export const IconDollarSign: typeof import("../components/icon/icon-dollar-sign.vue")['default']
export const IconDownload: typeof import("../components/icon/icon-download.vue")['default']
export const IconDribbble: typeof import("../components/icon/icon-dribbble.vue")['default']
export const IconDroplet: typeof import("../components/icon/icon-droplet.vue")['default']
export const IconEdit: typeof import("../components/icon/icon-edit.vue")['default']
export const IconEthereum: typeof import("../components/icon/icon-ethereum.vue")['default']
export const IconEye: typeof import("../components/icon/icon-eye.vue")['default']
export const IconFacebookCircle: typeof import("../components/icon/icon-facebook-circle.vue")['default']
export const IconFacebook: typeof import("../components/icon/icon-facebook.vue")['default']
export const IconFile: typeof import("../components/icon/icon-file.vue")['default']
export const IconFolderMinus: typeof import("../components/icon/icon-folder-minus.vue")['default']
export const IconFolderPlus: typeof import("../components/icon/icon-folder-plus.vue")['default']
export const IconFolder: typeof import("../components/icon/icon-folder.vue")['default']
export const IconGallery: typeof import("../components/icon/icon-gallery.vue")['default']
export const IconGithub: typeof import("../components/icon/icon-github.vue")['default']
export const IconGlobe: typeof import("../components/icon/icon-globe.vue")['default']
export const IconGoogle: typeof import("../components/icon/icon-google.vue")['default']
export const IconHeart: typeof import("../components/icon/icon-heart.vue")['default']
export const IconHelpCircle: typeof import("../components/icon/icon-help-circle.vue")['default']
export const IconHome: typeof import("../components/icon/icon-home.vue")['default']
export const IconHorizontalDots: typeof import("../components/icon/icon-horizontal-dots.vue")['default']
export const IconInbox: typeof import("../components/icon/icon-inbox.vue")['default']
export const IconInfoCircle: typeof import("../components/icon/icon-info-circle.vue")['default']
export const IconInfoHexagon: typeof import("../components/icon/icon-info-hexagon.vue")['default']
export const IconInfoTriangle: typeof import("../components/icon/icon-info-triangle.vue")['default']
export const IconInstagram: typeof import("../components/icon/icon-instagram.vue")['default']
export const IconLaptop: typeof import("../components/icon/icon-laptop.vue")['default']
export const IconLayoutGrid: typeof import("../components/icon/icon-layout-grid.vue")['default']
export const IconLayout: typeof import("../components/icon/icon-layout.vue")['default']
export const IconLink: typeof import("../components/icon/icon-link.vue")['default']
export const IconLinkedin: typeof import("../components/icon/icon-linkedin.vue")['default']
export const IconListCheck: typeof import("../components/icon/icon-list-check.vue")['default']
export const IconLitecoin: typeof import("../components/icon/icon-litecoin.vue")['default']
export const IconLoader: typeof import("../components/icon/icon-loader.vue")['default']
export const IconLockDots: typeof import("../components/icon/icon-lock-dots.vue")['default']
export const IconLock: typeof import("../components/icon/icon-lock.vue")['default']
export const IconLogin: typeof import("../components/icon/icon-login.vue")['default']
export const IconLogout: typeof import("../components/icon/icon-logout.vue")['default']
export const IconMailDot: typeof import("../components/icon/icon-mail-dot.vue")['default']
export const IconMail: typeof import("../components/icon/icon-mail.vue")['default']
export const IconMapPin: typeof import("../components/icon/icon-map-pin.vue")['default']
export const IconMenu: typeof import("../components/icon/icon-menu.vue")['default']
export const IconMessage2: typeof import("../components/icon/icon-message-2.vue")['default']
export const IconMessageDots: typeof import("../components/icon/icon-message-dots.vue")['default']
export const IconMessage: typeof import("../components/icon/icon-message.vue")['default']
export const IconMessagesDot: typeof import("../components/icon/icon-messages-dot.vue")['default']
export const IconMicrophoneOff: typeof import("../components/icon/icon-microphone-off.vue")['default']
export const IconMinusCircle: typeof import("../components/icon/icon-minus-circle.vue")['default']
export const IconMinus: typeof import("../components/icon/icon-minus.vue")['default']
export const IconMoodSmile: typeof import("../components/icon/icon-mood-smile.vue")['default']
export const IconMoon: typeof import("../components/icon/icon-moon.vue")['default']
export const IconMultipleForwardRight: typeof import("../components/icon/icon-multiple-forward-right.vue")['default']
export const IconNetflix: typeof import("../components/icon/icon-netflix.vue")['default']
export const IconNotesEdit: typeof import("../components/icon/icon-notes-edit.vue")['default']
export const IconNotes: typeof import("../components/icon/icon-notes.vue")['default']
export const IconOpenBook: typeof import("../components/icon/icon-open-book.vue")['default']
export const IconPaperclip: typeof import("../components/icon/icon-paperclip.vue")['default']
export const IconPencilPaper: typeof import("../components/icon/icon-pencil-paper.vue")['default']
export const IconPencil: typeof import("../components/icon/icon-pencil.vue")['default']
export const IconPhoneCall: typeof import("../components/icon/icon-phone-call.vue")['default']
export const IconPhone: typeof import("../components/icon/icon-phone.vue")['default']
export const IconPlayCircle: typeof import("../components/icon/icon-play-circle.vue")['default']
export const IconPlusCircle: typeof import("../components/icon/icon-plus-circle.vue")['default']
export const IconPlus: typeof import("../components/icon/icon-plus.vue")['default']
export const IconPrinter: typeof import("../components/icon/icon-printer.vue")['default']
export const IconRefresh: typeof import("../components/icon/icon-refresh.vue")['default']
export const IconRestore: typeof import("../components/icon/icon-restore.vue")['default']
export const IconRouter: typeof import("../components/icon/icon-router.vue")['default']
export const IconSafari: typeof import("../components/icon/icon-safari.vue")['default']
export const IconSave: typeof import("../components/icon/icon-save.vue")['default']
export const IconSearch: typeof import("../components/icon/icon-search.vue")['default']
export const IconSend: typeof import("../components/icon/icon-send.vue")['default']
export const IconServer: typeof import("../components/icon/icon-server.vue")['default']
export const IconSettings: typeof import("../components/icon/icon-settings.vue")['default']
export const IconShare: typeof import("../components/icon/icon-share.vue")['default']
export const IconShoppingBag: typeof import("../components/icon/icon-shopping-bag.vue")['default']
export const IconShoppingCart: typeof import("../components/icon/icon-shopping-cart.vue")['default']
export const IconSolana: typeof import("../components/icon/icon-solana.vue")['default']
export const IconSquareCheck: typeof import("../components/icon/icon-square-check.vue")['default']
export const IconSquareRotated: typeof import("../components/icon/icon-square-rotated.vue")['default']
export const IconStar: typeof import("../components/icon/icon-star.vue")['default']
export const IconSun: typeof import("../components/icon/icon-sun.vue")['default']
export const IconTag: typeof import("../components/icon/icon-tag.vue")['default']
export const IconTether: typeof import("../components/icon/icon-tether.vue")['default']
export const IconThumbUp: typeof import("../components/icon/icon-thumb-up.vue")['default']
export const IconTrashLines: typeof import("../components/icon/icon-trash-lines.vue")['default']
export const IconTrash: typeof import("../components/icon/icon-trash.vue")['default']
export const IconTrendingUp: typeof import("../components/icon/icon-trending-up.vue")['default']
export const IconTwitter: typeof import("../components/icon/icon-twitter.vue")['default']
export const IconTxtFile: typeof import("../components/icon/icon-txt-file.vue")['default']
export const IconUserPlus: typeof import("../components/icon/icon-user-plus.vue")['default']
export const IconUser: typeof import("../components/icon/icon-user.vue")['default']
export const IconUsersGroup: typeof import("../components/icon/icon-users-group.vue")['default']
export const IconUsers: typeof import("../components/icon/icon-users.vue")['default']
export const IconVideo: typeof import("../components/icon/icon-video.vue")['default']
export const IconWheel: typeof import("../components/icon/icon-wheel.vue")['default']
export const IconXCircle: typeof import("../components/icon/icon-x-circle.vue")['default']
export const IconX: typeof import("../components/icon/icon-x.vue")['default']
export const IconZipFile: typeof import("../components/icon/icon-zip-file.vue")['default']
export const IconMenuApps: typeof import("../components/icon/menu/icon-menu-apps.vue")['default']
export const IconMenuAuthentication: typeof import("../components/icon/menu/icon-menu-authentication.vue")['default']
export const IconMenuCalendar: typeof import("../components/icon/menu/icon-menu-calendar.vue")['default']
export const IconMenuCharts: typeof import("../components/icon/menu/icon-menu-charts.vue")['default']
export const IconMenuChat: typeof import("../components/icon/menu/icon-menu-chat.vue")['default']
export const IconMenuComponents: typeof import("../components/icon/menu/icon-menu-components.vue")['default']
export const IconMenuContacts: typeof import("../components/icon/menu/icon-menu-contacts.vue")['default']
export const IconMenuDashboard: typeof import("../components/icon/menu/icon-menu-dashboard.vue")['default']
export const IconMenuDatatables: typeof import("../components/icon/menu/icon-menu-datatables.vue")['default']
export const IconMenuDocumentation: typeof import("../components/icon/menu/icon-menu-documentation.vue")['default']
export const IconMenuDragAndDrop: typeof import("../components/icon/menu/icon-menu-drag-and-drop.vue")['default']
export const IconMenuElements: typeof import("../components/icon/menu/icon-menu-elements.vue")['default']
export const IconMenuFontIcons: typeof import("../components/icon/menu/icon-menu-font-icons.vue")['default']
export const IconMenuForms: typeof import("../components/icon/menu/icon-menu-forms.vue")['default']
export const IconMenuInvoice: typeof import("../components/icon/menu/icon-menu-invoice.vue")['default']
export const IconMenuMailbox: typeof import("../components/icon/menu/icon-menu-mailbox.vue")['default']
export const IconMenuMore: typeof import("../components/icon/menu/icon-menu-more.vue")['default']
export const IconMenuNotes: typeof import("../components/icon/menu/icon-menu-notes.vue")['default']
export const IconMenuPages: typeof import("../components/icon/menu/icon-menu-pages.vue")['default']
export const IconMenuScrumboard: typeof import("../components/icon/menu/icon-menu-scrumboard.vue")['default']
export const IconMenuTables: typeof import("../components/icon/menu/icon-menu-tables.vue")['default']
export const IconMenuTodo: typeof import("../components/icon/menu/icon-menu-todo.vue")['default']
export const IconMenuUsers: typeof import("../components/icon/menu/icon-menu-users.vue")['default']
export const IconMenuWidgets: typeof import("../components/icon/menu/icon-menu-widgets.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LayoutSidebar: typeof import("../components/layout/Sidebar.vue")['default']
export const MatterAdd: typeof import("../components/matter/Add.vue")['default']
export const PluginsHighlight: typeof import("../components/plugins/highlight.vue")['default']
export const TaskAdd: typeof import("../components/task/Add.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyThemeCustomizer: typeof import("../components/ThemeCustomizer.vue")['default']
export const LazyBaseDatePicker: typeof import("../components/base/DatePicker.vue")['default']
export const LazyBaseModal: typeof import("../components/base/Modal.vue")['default']
export const LazyBaseMultiSelect: typeof import("../components/base/MultiSelect.vue")['default']
export const LazyBaseMultiSelectt: typeof import("../components/base/MultiSelectt.vue")['default']
export const LazyBaseUpload: typeof import("../components/base/Upload.vue")['default']
export const LazyClientAddClient: typeof import("../components/client/AddClient.vue")['default']
export const LazyClientTag: typeof import("../components/client/Tag.vue")['default']
export const LazyFormCheckbox: typeof import("../components/form/Checkbox.vue")['default']
export const LazyFormInput: typeof import("../components/form/Input.vue")['default']
export const LazyFormPriceInput: typeof import("../components/form/PriceInput.vue")['default']
export const LazyFormRadio: typeof import("../components/form/Radio.vue")['default']
export const LazyFormTextarea: typeof import("../components/form/Textarea.vue")['default']
export const LazyIconCompany: typeof import("../components/icon/Company.vue")['default']
export const LazyIconAirplay: typeof import("../components/icon/icon-airplay.vue")['default']
export const LazyIconArchive: typeof import("../components/icon/icon-archive.vue")['default']
export const LazyIconArrowBackward: typeof import("../components/icon/icon-arrow-backward.vue")['default']
export const LazyIconArrowForward: typeof import("../components/icon/icon-arrow-forward.vue")['default']
export const LazyIconArrowLeft: typeof import("../components/icon/icon-arrow-left.vue")['default']
export const LazyIconArrowWaveLeftUp: typeof import("../components/icon/icon-arrow-wave-left-up.vue")['default']
export const LazyIconAt: typeof import("../components/icon/icon-at.vue")['default']
export const LazyIconAward: typeof import("../components/icon/icon-award.vue")['default']
export const LazyIconBarChart: typeof import("../components/icon/icon-bar-chart.vue")['default']
export const LazyIconBellBing: typeof import("../components/icon/icon-bell-bing.vue")['default']
export const LazyIconBell: typeof import("../components/icon/icon-bell.vue")['default']
export const LazyIconBinance: typeof import("../components/icon/icon-binance.vue")['default']
export const LazyIconBitcoin: typeof import("../components/icon/icon-bitcoin.vue")['default']
export const LazyIconBolt: typeof import("../components/icon/icon-bolt.vue")['default']
export const LazyIconBook: typeof import("../components/icon/icon-book.vue")['default']
export const LazyIconBookmark: typeof import("../components/icon/icon-bookmark.vue")['default']
export const LazyIconBox: typeof import("../components/icon/icon-box.vue")['default']
export const LazyIconCalendar: typeof import("../components/icon/icon-calendar.vue")['default']
export const LazyIconCamera: typeof import("../components/icon/icon-camera.vue")['default']
export const LazyIconCaretDown: typeof import("../components/icon/icon-caret-down.vue")['default']
export const LazyIconCaretsDown: typeof import("../components/icon/icon-carets-down.vue")['default']
export const LazyIconCashBanknotes: typeof import("../components/icon/icon-cash-banknotes.vue")['default']
export const LazyIconChartSquare: typeof import("../components/icon/icon-chart-square.vue")['default']
export const LazyIconChatDot: typeof import("../components/icon/icon-chat-dot.vue")['default']
export const LazyIconChatDots: typeof import("../components/icon/icon-chat-dots.vue")['default']
export const LazyIconChatNotification: typeof import("../components/icon/icon-chat-notification.vue")['default']
export const LazyIconChecks: typeof import("../components/icon/icon-checks.vue")['default']
export const LazyIconChrome: typeof import("../components/icon/icon-chrome.vue")['default']
export const LazyIconCircleCheck: typeof import("../components/icon/icon-circle-check.vue")['default']
export const LazyIconClipboardText: typeof import("../components/icon/icon-clipboard-text.vue")['default']
export const LazyIconClock: typeof import("../components/icon/icon-clock.vue")['default']
export const LazyIconCloudDownload: typeof import("../components/icon/icon-cloud-download.vue")['default']
export const LazyIconCode: typeof import("../components/icon/icon-code.vue")['default']
export const LazyIconCoffee: typeof import("../components/icon/icon-coffee.vue")['default']
export const LazyIconCopy: typeof import("../components/icon/icon-copy.vue")['default']
export const LazyIconCpuBolt: typeof import("../components/icon/icon-cpu-bolt.vue")['default']
export const LazyIconCreditCard: typeof import("../components/icon/icon-credit-card.vue")['default']
export const LazyIconDesktop: typeof import("../components/icon/icon-desktop.vue")['default']
export const LazyIconDollarSignCircle: typeof import("../components/icon/icon-dollar-sign-circle.vue")['default']
export const LazyIconDollarSign: typeof import("../components/icon/icon-dollar-sign.vue")['default']
export const LazyIconDownload: typeof import("../components/icon/icon-download.vue")['default']
export const LazyIconDribbble: typeof import("../components/icon/icon-dribbble.vue")['default']
export const LazyIconDroplet: typeof import("../components/icon/icon-droplet.vue")['default']
export const LazyIconEdit: typeof import("../components/icon/icon-edit.vue")['default']
export const LazyIconEthereum: typeof import("../components/icon/icon-ethereum.vue")['default']
export const LazyIconEye: typeof import("../components/icon/icon-eye.vue")['default']
export const LazyIconFacebookCircle: typeof import("../components/icon/icon-facebook-circle.vue")['default']
export const LazyIconFacebook: typeof import("../components/icon/icon-facebook.vue")['default']
export const LazyIconFile: typeof import("../components/icon/icon-file.vue")['default']
export const LazyIconFolderMinus: typeof import("../components/icon/icon-folder-minus.vue")['default']
export const LazyIconFolderPlus: typeof import("../components/icon/icon-folder-plus.vue")['default']
export const LazyIconFolder: typeof import("../components/icon/icon-folder.vue")['default']
export const LazyIconGallery: typeof import("../components/icon/icon-gallery.vue")['default']
export const LazyIconGithub: typeof import("../components/icon/icon-github.vue")['default']
export const LazyIconGlobe: typeof import("../components/icon/icon-globe.vue")['default']
export const LazyIconGoogle: typeof import("../components/icon/icon-google.vue")['default']
export const LazyIconHeart: typeof import("../components/icon/icon-heart.vue")['default']
export const LazyIconHelpCircle: typeof import("../components/icon/icon-help-circle.vue")['default']
export const LazyIconHome: typeof import("../components/icon/icon-home.vue")['default']
export const LazyIconHorizontalDots: typeof import("../components/icon/icon-horizontal-dots.vue")['default']
export const LazyIconInbox: typeof import("../components/icon/icon-inbox.vue")['default']
export const LazyIconInfoCircle: typeof import("../components/icon/icon-info-circle.vue")['default']
export const LazyIconInfoHexagon: typeof import("../components/icon/icon-info-hexagon.vue")['default']
export const LazyIconInfoTriangle: typeof import("../components/icon/icon-info-triangle.vue")['default']
export const LazyIconInstagram: typeof import("../components/icon/icon-instagram.vue")['default']
export const LazyIconLaptop: typeof import("../components/icon/icon-laptop.vue")['default']
export const LazyIconLayoutGrid: typeof import("../components/icon/icon-layout-grid.vue")['default']
export const LazyIconLayout: typeof import("../components/icon/icon-layout.vue")['default']
export const LazyIconLink: typeof import("../components/icon/icon-link.vue")['default']
export const LazyIconLinkedin: typeof import("../components/icon/icon-linkedin.vue")['default']
export const LazyIconListCheck: typeof import("../components/icon/icon-list-check.vue")['default']
export const LazyIconLitecoin: typeof import("../components/icon/icon-litecoin.vue")['default']
export const LazyIconLoader: typeof import("../components/icon/icon-loader.vue")['default']
export const LazyIconLockDots: typeof import("../components/icon/icon-lock-dots.vue")['default']
export const LazyIconLock: typeof import("../components/icon/icon-lock.vue")['default']
export const LazyIconLogin: typeof import("../components/icon/icon-login.vue")['default']
export const LazyIconLogout: typeof import("../components/icon/icon-logout.vue")['default']
export const LazyIconMailDot: typeof import("../components/icon/icon-mail-dot.vue")['default']
export const LazyIconMail: typeof import("../components/icon/icon-mail.vue")['default']
export const LazyIconMapPin: typeof import("../components/icon/icon-map-pin.vue")['default']
export const LazyIconMenu: typeof import("../components/icon/icon-menu.vue")['default']
export const LazyIconMessage2: typeof import("../components/icon/icon-message-2.vue")['default']
export const LazyIconMessageDots: typeof import("../components/icon/icon-message-dots.vue")['default']
export const LazyIconMessage: typeof import("../components/icon/icon-message.vue")['default']
export const LazyIconMessagesDot: typeof import("../components/icon/icon-messages-dot.vue")['default']
export const LazyIconMicrophoneOff: typeof import("../components/icon/icon-microphone-off.vue")['default']
export const LazyIconMinusCircle: typeof import("../components/icon/icon-minus-circle.vue")['default']
export const LazyIconMinus: typeof import("../components/icon/icon-minus.vue")['default']
export const LazyIconMoodSmile: typeof import("../components/icon/icon-mood-smile.vue")['default']
export const LazyIconMoon: typeof import("../components/icon/icon-moon.vue")['default']
export const LazyIconMultipleForwardRight: typeof import("../components/icon/icon-multiple-forward-right.vue")['default']
export const LazyIconNetflix: typeof import("../components/icon/icon-netflix.vue")['default']
export const LazyIconNotesEdit: typeof import("../components/icon/icon-notes-edit.vue")['default']
export const LazyIconNotes: typeof import("../components/icon/icon-notes.vue")['default']
export const LazyIconOpenBook: typeof import("../components/icon/icon-open-book.vue")['default']
export const LazyIconPaperclip: typeof import("../components/icon/icon-paperclip.vue")['default']
export const LazyIconPencilPaper: typeof import("../components/icon/icon-pencil-paper.vue")['default']
export const LazyIconPencil: typeof import("../components/icon/icon-pencil.vue")['default']
export const LazyIconPhoneCall: typeof import("../components/icon/icon-phone-call.vue")['default']
export const LazyIconPhone: typeof import("../components/icon/icon-phone.vue")['default']
export const LazyIconPlayCircle: typeof import("../components/icon/icon-play-circle.vue")['default']
export const LazyIconPlusCircle: typeof import("../components/icon/icon-plus-circle.vue")['default']
export const LazyIconPlus: typeof import("../components/icon/icon-plus.vue")['default']
export const LazyIconPrinter: typeof import("../components/icon/icon-printer.vue")['default']
export const LazyIconRefresh: typeof import("../components/icon/icon-refresh.vue")['default']
export const LazyIconRestore: typeof import("../components/icon/icon-restore.vue")['default']
export const LazyIconRouter: typeof import("../components/icon/icon-router.vue")['default']
export const LazyIconSafari: typeof import("../components/icon/icon-safari.vue")['default']
export const LazyIconSave: typeof import("../components/icon/icon-save.vue")['default']
export const LazyIconSearch: typeof import("../components/icon/icon-search.vue")['default']
export const LazyIconSend: typeof import("../components/icon/icon-send.vue")['default']
export const LazyIconServer: typeof import("../components/icon/icon-server.vue")['default']
export const LazyIconSettings: typeof import("../components/icon/icon-settings.vue")['default']
export const LazyIconShare: typeof import("../components/icon/icon-share.vue")['default']
export const LazyIconShoppingBag: typeof import("../components/icon/icon-shopping-bag.vue")['default']
export const LazyIconShoppingCart: typeof import("../components/icon/icon-shopping-cart.vue")['default']
export const LazyIconSolana: typeof import("../components/icon/icon-solana.vue")['default']
export const LazyIconSquareCheck: typeof import("../components/icon/icon-square-check.vue")['default']
export const LazyIconSquareRotated: typeof import("../components/icon/icon-square-rotated.vue")['default']
export const LazyIconStar: typeof import("../components/icon/icon-star.vue")['default']
export const LazyIconSun: typeof import("../components/icon/icon-sun.vue")['default']
export const LazyIconTag: typeof import("../components/icon/icon-tag.vue")['default']
export const LazyIconTether: typeof import("../components/icon/icon-tether.vue")['default']
export const LazyIconThumbUp: typeof import("../components/icon/icon-thumb-up.vue")['default']
export const LazyIconTrashLines: typeof import("../components/icon/icon-trash-lines.vue")['default']
export const LazyIconTrash: typeof import("../components/icon/icon-trash.vue")['default']
export const LazyIconTrendingUp: typeof import("../components/icon/icon-trending-up.vue")['default']
export const LazyIconTwitter: typeof import("../components/icon/icon-twitter.vue")['default']
export const LazyIconTxtFile: typeof import("../components/icon/icon-txt-file.vue")['default']
export const LazyIconUserPlus: typeof import("../components/icon/icon-user-plus.vue")['default']
export const LazyIconUser: typeof import("../components/icon/icon-user.vue")['default']
export const LazyIconUsersGroup: typeof import("../components/icon/icon-users-group.vue")['default']
export const LazyIconUsers: typeof import("../components/icon/icon-users.vue")['default']
export const LazyIconVideo: typeof import("../components/icon/icon-video.vue")['default']
export const LazyIconWheel: typeof import("../components/icon/icon-wheel.vue")['default']
export const LazyIconXCircle: typeof import("../components/icon/icon-x-circle.vue")['default']
export const LazyIconX: typeof import("../components/icon/icon-x.vue")['default']
export const LazyIconZipFile: typeof import("../components/icon/icon-zip-file.vue")['default']
export const LazyIconMenuApps: typeof import("../components/icon/menu/icon-menu-apps.vue")['default']
export const LazyIconMenuAuthentication: typeof import("../components/icon/menu/icon-menu-authentication.vue")['default']
export const LazyIconMenuCalendar: typeof import("../components/icon/menu/icon-menu-calendar.vue")['default']
export const LazyIconMenuCharts: typeof import("../components/icon/menu/icon-menu-charts.vue")['default']
export const LazyIconMenuChat: typeof import("../components/icon/menu/icon-menu-chat.vue")['default']
export const LazyIconMenuComponents: typeof import("../components/icon/menu/icon-menu-components.vue")['default']
export const LazyIconMenuContacts: typeof import("../components/icon/menu/icon-menu-contacts.vue")['default']
export const LazyIconMenuDashboard: typeof import("../components/icon/menu/icon-menu-dashboard.vue")['default']
export const LazyIconMenuDatatables: typeof import("../components/icon/menu/icon-menu-datatables.vue")['default']
export const LazyIconMenuDocumentation: typeof import("../components/icon/menu/icon-menu-documentation.vue")['default']
export const LazyIconMenuDragAndDrop: typeof import("../components/icon/menu/icon-menu-drag-and-drop.vue")['default']
export const LazyIconMenuElements: typeof import("../components/icon/menu/icon-menu-elements.vue")['default']
export const LazyIconMenuFontIcons: typeof import("../components/icon/menu/icon-menu-font-icons.vue")['default']
export const LazyIconMenuForms: typeof import("../components/icon/menu/icon-menu-forms.vue")['default']
export const LazyIconMenuInvoice: typeof import("../components/icon/menu/icon-menu-invoice.vue")['default']
export const LazyIconMenuMailbox: typeof import("../components/icon/menu/icon-menu-mailbox.vue")['default']
export const LazyIconMenuMore: typeof import("../components/icon/menu/icon-menu-more.vue")['default']
export const LazyIconMenuNotes: typeof import("../components/icon/menu/icon-menu-notes.vue")['default']
export const LazyIconMenuPages: typeof import("../components/icon/menu/icon-menu-pages.vue")['default']
export const LazyIconMenuScrumboard: typeof import("../components/icon/menu/icon-menu-scrumboard.vue")['default']
export const LazyIconMenuTables: typeof import("../components/icon/menu/icon-menu-tables.vue")['default']
export const LazyIconMenuTodo: typeof import("../components/icon/menu/icon-menu-todo.vue")['default']
export const LazyIconMenuUsers: typeof import("../components/icon/menu/icon-menu-users.vue")['default']
export const LazyIconMenuWidgets: typeof import("../components/icon/menu/icon-menu-widgets.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyLayoutSidebar: typeof import("../components/layout/Sidebar.vue")['default']
export const LazyMatterAdd: typeof import("../components/matter/Add.vue")['default']
export const LazyPluginsHighlight: typeof import("../components/plugins/highlight.vue")['default']
export const LazyTaskAdd: typeof import("../components/task/Add.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
